import './globals.css'
import { Inter } from 'next/font/google'
import Header from "../components/Header/page"
import Footer from "../components/Footer/page"
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        <main>
        {children}
        </main>
        
        <Footer/>
      </body>
    </html>
  )
}
